### ISSUE TITLE
Error on creating a topic (java.io.FileNotFoundException: /cluster-dev-topics.yml)

### ISSUE THREAD

**Issue by prabago** [streamthoughts/kafka-specs#17]
Hi,

I'm trying to create a topic through the command:

```console
docker run -it --net host \
-v $(pwd)/kafka-specs.yaml:/kafka-specs.yaml \
streamthoughts/kafka-specs \
--file /cluster-dev-topics.yml \
--bootstrap-server localhost:9092 \
--execute --create \
--entity-type topics \
--verbose
```

I have raised an instance of kafka in local and if I run sh 

```console
./kafka-topics.sh --create --bootstrap-server localhost:9092 --replication-factor 1 --partitions 1 --topic TutorialTopic3
```
`Created topic TutorialTopic3.`

However if I run it through kafka-specs it gives me an error:

`java.lang.RuntimeException: java.io.FileNotFoundException: /cluster-dev-topics.yml (No such file or directory)`

If execute the command:
```console
docker run --net host \
> streamthoughts/kafka-specs \
> --bootstrap-server localhost:9092 \
> --describe \
> --entity-type topics \
> --default-configs
```
It returns me the correct configuration of the kafka server
```yaml
topics:
- name: TutorialTopic2
  partitions: 1
  replication_factor: 1
  configs:
    cleanup.policy: delete
    compression.type: producer
    delete.retention.ms: '86400000'
    file.delete.delay.ms: '60000'
    flush.messages: '9223372036854775807'
    flush.ms: '9223372036854775807'
    follower.replication.throttled.replicas: ''
    index.interval.bytes: '4096'
    leader.replication.throttled.replicas: ''
    max.compaction.lag.ms: '9223372036854775807'
    max.message.bytes: '1048588'
    message.downconversion.enable: 'true'
    message.format.version: 2.5-IV0
    message.timestamp.difference.max.ms: '9223372036854775807'
    message.timestamp.type: CreateTime
    min.cleanable.dirty.ratio: '0.5'
    min.compaction.lag.ms: '0'
    min.insync.replicas: '1'
    preallocate: 'false'
    retention.bytes: '-1'
    retention.ms: '604800000'
    segment.bytes: '1073741824'
    segment.index.bytes: '10485760'
    segment.jitter.ms: '0'
    segment.ms: '604800000'
    unclean.leader.election.enable: 'false'
- name: TutorialTopic1
  partitions: 1
  replication_factor: 1
  configs:
    cleanup.policy: delete
    compression.type: producer
    delete.retention.ms: '86400000'
    file.delete.delay.ms: '60000'
    flush.messages: '9223372036854775807'
    flush.ms: '9223372036854775807'
    follower.replication.throttled.replicas: ''
    index.interval.bytes: '4096'
    leader.replication.throttled.replicas: ''
    max.compaction.lag.ms: '9223372036854775807'
    max.message.bytes: '1048588'
    message.downconversion.enable: 'true'
    message.format.version: 2.5-IV0
    message.timestamp.difference.max.ms: '9223372036854775807'
    message.timestamp.type: CreateTime
    min.cleanable.dirty.ratio: '0.5'
    min.compaction.lag.ms: '0'
    min.insync.replicas: '1'
    preallocate: 'false'
    retention.bytes: '-1'
    retention.ms: '604800000'
    segment.bytes: '1073741824'
    segment.index.bytes: '10485760'
    segment.jitter.ms: '0'
    segment.ms: '604800000'
    unclean.leader.election.enable: 'false'
- name: TutorialTopic3
  partitions: 1
  replication_factor: 1
  configs:
    cleanup.policy: delete
    compression.type: producer
    delete.retention.ms: '86400000'
    file.delete.delay.ms: '60000'
    flush.messages: '9223372036854775807'
    flush.ms: '9223372036854775807'
    follower.replication.throttled.replicas: ''
    index.interval.bytes: '4096'
    leader.replication.throttled.replicas: ''
    max.compaction.lag.ms: '9223372036854775807'
    max.message.bytes: '1048588'
    message.downconversion.enable: 'true'
    message.format.version: 2.5-IV0
    message.timestamp.difference.max.ms: '9223372036854775807'
    message.timestamp.type: CreateTime
    min.cleanable.dirty.ratio: '0.5'
    min.compaction.lag.ms: '0'
    min.insync.replicas: '1'
    preallocate: 'false'
    retention.bytes: '-1'
    retention.ms: '604800000'
    segment.bytes: '1073741824'
    segment.index.bytes: '10485760'
    segment.jitter.ms: '0'
    segment.ms: '604800000'
    unclean.leader.election.enable: 'false'
- name: TutorialTopic
  partitions: 1
  replication_factor: 1
  configs:
    cleanup.policy: delete
    compression.type: producer
    delete.retention.ms: '86400000'
    file.delete.delay.ms: '60000'
    flush.messages: '9223372036854775807'
    flush.ms: '9223372036854775807'
    follower.replication.throttled.replicas: ''
    index.interval.bytes: '4096'
    leader.replication.throttled.replicas: ''
    max.compaction.lag.ms: '9223372036854775807'
    max.message.bytes: '1048588'
    message.downconversion.enable: 'true'
    message.format.version: 2.5-IV0
    message.timestamp.difference.max.ms: '9223372036854775807'
    message.timestamp.type: CreateTime
    min.cleanable.dirty.ratio: '0.5'
    min.compaction.lag.ms: '0'
    min.insync.replicas: '1'
    preallocate: 'false'
    retention.bytes: '-1'
    retention.ms: '604800000'
    segment.bytes: '1073741824'
    segment.index.bytes: '10485760'
    segment.jitter.ms: '0'
    segment.ms: '604800000'
    unclean.leader.election.enable: 'false'
```

Attached are the captures.

![image](https://user-images.githubusercontent.com/25517820/87658710-db657700-c75c-11ea-94c7-a0a022ec3f19.png)

Thank you very much in advance.

Greetings.
