### ISSUE TITLE
Alter ande Delete Topics

### ISSUE THREAD

**Issue by prabago** [streamthoughts/kafka-specs#18]
Hello,

I have a question regarding the alter option, 

I've created a topic with the following configuration:
```yaml
version: 1
topics:
- configs:
    cleanup.policy: compact
    compression.type: producer
    min.insync.replicas: '1'
    retention.ms: '1000'
    max.message.bytes: '64000'
    flush.messages: '1'
  name: prueba-v2
  partitions: 10
  replication_factor: 1
```
when i excuted _describe_ the configuration of that topic is shown:

```console
../kafka/kafka/bin/./kafka-topics.sh --describe --zookeeper localhost:2181 --topic prueba-v2
Topic: prueba-v2	PartitionCount: 10	ReplicationFactor: 1	Configs: compression.type=producer,cleanup.policy=compact,max.message.bytes=64000,min.insync.replicas=1,retention.ms=1000,flush.messages=1
	Topic: prueba-v2	Partition: 0	Leader: 0	Replicas: 0	Isr: 0
	Topic: prueba-v2	Partition: 1	Leader: 0	Replicas: 0	Isr: 0
	Topic: prueba-v2	Partition: 2	Leader: 0	Replicas: 0	Isr: 0
	Topic: prueba-v2	Partition: 3	Leader: 0	Replicas: 0	Isr: 0
	Topic: prueba-v2	Partition: 4	Leader: 0	Replicas: 0	Isr: 0
	Topic: prueba-v2	Partition: 5	Leader: 0	Replicas: 0	Isr: 0
	Topic: prueba-v2	Partition: 6	Leader: 0	Replicas: 0	Isr: 0
	Topic: prueba-v2	Partition: 7	Leader: 0	Replicas: 0	Isr: 0
	Topic: prueba-v2	Partition: 8	Leader: 0	Replicas: 0	Isr: 0
	Topic: prueba-v2	Partition: 9	Leader: 0	Replicas: 0	Isr: 0
```
Now I'm going to modify the **_max.message.bytes_** property and assign it the value from **_64000_** to **_128000_**

```yaml
version: 1
topics:
- configs:
    cleanup.policy: compact
    compression.type: producer
    min.insync.replicas: '1'
    retention.ms: '1000'
    max.message.bytes: '128000'
    flush.messages: '1'
  name: prueba-v2
  partitions: 10
  replication_factor: 1
```
When I execute command:
```console
docker run -it --net host -v $(pwd)/kafka-specs.yaml:/kafka-specs.yaml streamthoughts/kafka-specs --file /kafka-specs.yaml --bootstrap-server localhost:9092  --execute --alter --entity-type topics --verbose --yes
```
![image](https://user-images.githubusercontent.com/25517820/87930199-ee8f8400-ca87-11ea-86b9-c4ed3c1ea0ae.png)
It indicates to me that you have not performed any operations
**ok : 0, changed : 0, failed : 0**

You know what I might be missing?
It's the same with the **delete**

![image](https://user-images.githubusercontent.com/25517820/87930941-3bc02580-ca89-11ea-815b-5e1841788551.png)

Thanks in advance!!

Regards!
